chore: refactor error handling code
- `ok_or` transforms an `Option` into a `Result`. If the value is `Some(x)` then we get `Ok(x)` otherwise `None` becomes an `Err` and we supply the required error value in the parentheses.
- we abstract away all the error handling stuff and focus on important behaviour of get path, open file, count lines. errors are checked and dealt with automatically wherever we use `?`.

```
➜  wcrs git:(main) cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/wcrs`
Error: Custom { kind: Other, error: "Usage: count <FILE>" }
➜  wcrs git:(main) cargo run bogus
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/wcrs bogus`
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
➜  wcrs git:(main) cargo run .
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/wcrs .`
Error: Os { code: 21, kind: IsADirectory, message: "Is a directory" }
```