chore: use anyhow::Result
- better error messages:
- function returns `anyhow::Result` and therefore any error encountered with `?` is transformed into `anyhow::Error` which accepts any kind of standard library error including `io::Error` and custom messages and prints them nicely using `Display`.

```
➜  wcrs git:(main) ✗ cargo run
   Compiling anyhow v1.0.100
   Compiling wcrs v0.1.0 (/Users/scr00ge/Workbench/wcrs)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/wcrs`
Error: Usage: count <FILE>
➜  wcrs git:(main) ✗ cargo run bogus
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/wcrs bogus`
Error: No such file or directory (os error 2)
➜  wcrs git:(main) ✗ cargo run .
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/wcrs .`
Error: Is a directory (os error 21)
```